server:
  port: ${SERVER_PORT:8080}
  tomcat:
    mbeanregistry:
      enabled: true
#management:
#  server:
#    port: ${ACTUATOR_PORT:${SERVER_PORT:8080}}
#  endpoints:
#    web:
#      exposure:
#        include: health, prometheus, refresh

#dsp:
#  oauth:
#    jwt:
#      public-key: |
#        -----BEGIN PUBLIC KEY-----
#        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoc1f/Y+ir3rXeKTwcPUT
#        RbFB+kMESkN/mh559C5buAYm64+A36dY1C9QogFI7iHtDqoPyd7qTAOVt0FmiRKm
#        N2jwBkKJR2y3Pt2Jq+c2DaXu22pIh7SiGXrjZZ49efxCSXUXp0tBtTOTB9IlXPNN
#        6F5dULb1MqiUlTZhs5aHsMGt38+QFupczyiFj1YRlqlNU1NZ58FiC1F26eaJ55Pe
#        h978zgkSCjSGaBsMUSOIXjLoXL68pqGpsQUM/s7oNfHlwZMDY4kxNTmVGyQgcqWf
#        kmf6+wLoQqXxCW0OQzLwUtJgnriw2+I/bnr0tLVYcyJ+6ZaMZxkhVzqrCToqEghU
#        OQIDAQAB
#        -----END PUBLIC KEY-----
#    enabled: true
#  error-handling:
#    enabled: true

## uncomment if you do not require JWT security on your endpoints
#  paths:
#    exclude-dsl-interception: /**
#    exclude-security: /**

spring:
  application:
    name: partner-credentials-service
  data:
    mongodb:
      uri: mongodb://Wayne:test@localhost:27017/config
  config:
    import: "vault://"
    enabled: false
  cloud:
    vault:
      token: 00000000-0000-0000-0000-000000000000
      scheme: http
      host: localhost
      enabled: true
      kv:
        enabled: true
      authentication: token
  zipkin:
    enabled: false

app:
  encryption-service: credentials


logging:
  level:
    root: INFO
